import re

filepath = 'src/data/physicsContentExt.ts'
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

def replace_topic(content, topic_name, new_text):
    pattern = r"(\s*'" + re.escape(topic_name) + r"': `)(.*?)(\n\s*`,?\n)"
    match = re.search(pattern, content, re.DOTALL)
    if not match:
        print(f"Could not find topic: {topic_name}")
        return content
    start_tag = match.group(1)
    end_tag = match.group(3)
    new_chunk = start_tag + "\n" + new_text + end_tag
    return content[:match.start()] + new_chunk + content[match.end():]

topics = {}

topics['Magnetism & Electromagnetism'] = r"""# Magnetism & Electromagnetism: The Twin Forces

## 1. The Source of Magnetism
Unlike electric charges (which can exist as isolated protons or electrons), magnetic poles *always* come in pairs (North and South). There is no such thing as a "magnetic monopole" in classical physics.
Fundamentally, all magnetic fields are generated by **moving electric charges**. A permanent magnet is magnetic because the electrons inside its atoms are orbiting and spinning in aligned directions, creating billions of microscopic current loops!

## 2. Magnetic Fields ($\vec{B}$)
Magnetic field lines point from North to South outside a magnet. 
When a moving charge enters a magnetic field, it experiences a force that is *perpendicular* to both its velocity and the magnetic field. This is calculated using the cross product:
$$ \vec{F}_B = q(\vec{v} \times \vec{B}) $$
Because the force is always perpendicular to velocity, a magnetic field can *never do work* on a moving charge; it can only change its direction, causing it to spiral or orbit.

## 3. Ampère's Law
Just as Gauss's Law links charge to Electric Fields, Ampère's Law links electric current ($I$) to Magnetic Fields. It states that the magnetic field integrated around a closed loop is proportional to the total current passing through that loop.
$$ \oint \vec{B} \cdot d\vec{s} = \mu_0 I_{enc} $$
(Where $\mu_0 = 4\pi \times 10^{-7}$ T$\cdot$m/A is the permeability of free space).

## 4. Faraday's Law of Induction
In 1831, Michael Faraday made a world-changing discovery: if moving charges create magnetic fields, then *changing magnetic fields can create electric currents*.
The induced Electromotive Force ($\mathcal{E}$) in a loop of wire is exactly equal to the negative rate of change of magnetic flux ($\Phi_B$) through the loop.
$$ \mathcal{E} = -\frac{d\Phi_B}{dt} $$
This single equation is the foundation of the modern electrical grid. Every power plant on Earth (except solar) generates electricity by physically spinning giant magnets inside coils of wire!

## 5. Lenz's Law
Notice the negative sign in Faraday's Law? That is Lenz's Law. It dictates that nature hates change. The induced current will always flow in a direction that creates its *own* magnetic field to oppose the original change in flux.

## Derivation of the Magnetic Field of a Solenoid
Use Ampère's Law to prove that the magnetic field inside an infinitely long, tightly wound solenoid (a coil of wire) is $B = \mu_0 n I$, where $n$ is the number of turns per unit length.

**Step 1:** Define the Amperian Loop.
Imagine a rectangular loop of length $L$ and width $w$. We place it so that one long side is exactly inside the solenoid (parallel to the central axis), and the other long side is far outside the solenoid.

**Step 2:** Evaluate the line integral $\oint \vec{B} \cdot d\vec{s}$ for all four sides.
* Side 1 (Inside, length $L$): The magnetic field is perfectly parallel to the path, so $\int \vec{B} \cdot d\vec{s} = B L$.
* Sides 2 & 4 (Perpendicular sides): The magnetic field is perpendicular to the path, so the dot product is exactly $0$.
* Side 3 (Far outside): The magnetic field outside an ideal infinite solenoid is $0$, so the integral is $0$.
Therefore:
$$ \oint \vec{B} \cdot d\vec{s} = B L $$

**Step 3:** Calculate the enclosed current $I_{enc}$.
The rectangular loop slices through the coils of the solenoid. If the solenoid has $n$ turns per unit length, then our loop of length $L$ encloses $N = nL$ turns of wire.
Since each turn carries current $I$, the total current passing through the rectangle is:
$$ I_{enc} = (nL)I $$

**Step 4:** Apply Ampère's Law.
$$ \oint \vec{B} \cdot d\vec{s} = \mu_0 I_{enc} $$
$$ B L = \mu_0 (nL) I $$

**Step 5:** Solve for $B$.
The arbitrary length $L$ perfectly cancels out!
$$ B = \mu_0 n I $$
Q.E.D. The magnetic field inside an ideal solenoid is perfectly uniform and depends only on the wire density and current.
"""

topics['Optics'] = r"""# Optics: The Physics of Light

## 1. The Nature of Light
For centuries, physicists argued over whether light was a wave or a particle. Thanks to Quantum Mechanics, we now know it exhibits wave-particle duality. In classical optics, however, we treat light strictly as an Electromagnetic Wave—an oscillating electric and magnetic field traveling through a vacuum at exactly $c = 299,792,458$ m/s.

## 2. Reflection and Refraction
When light strikes a boundary between two different transparent mediums (like air and water), two things happen:
* **Reflection**: The light bounces off. The angle of incidence exactly equals the angle of reflection ($\theta_i = \theta_r$).
* **Refraction**: The light bends as it enters the new medium because it slows down. The speed of light in a material is defined by its Index of Refraction ($n = c/v$). Water has $n = 1.33$, meaning light travels 33% slower in water than in a vacuum!

## 3. Snell's Law
The exact angle of bending during refraction is governed by Snell's Law:
$$ n_1 \sin\theta_1 = n_2 \sin\theta_2 $$

## 4. Total Internal Reflection
If light tries to exit a slow medium (like water, $n_1=1.33$) into a fast medium (like air, $n_2=1.0$), it bends *away* from the normal. At a specific "critical angle", it bends so far that it mathematically cannot exit the water at all, and acts as a perfect mirror!
$$ \theta_{crit} = \arcsin\left(\frac{n_2}{n_1}\right) $$
This phenomenon is how Fiber Optic cables transmit internet data across the ocean without losing any light!

## 5. Diffraction and Interference
Because light is a wave, it bends around sharp corners (Diffraction). When two light waves overlap, their peaks and troughs add together (Interference). If peak meets peak, you get bright Constructive Interference. If peak meets trough, they annihilate each other in dark Destructive Interference. This creates the beautiful rainbow patterns seen on soap bubbles and oil slicks.

## Derivation of Snell's Law (Fermat's Principle)
Fermat's Principle of Least Time states that light traveling between two points will always take the path that requires the absolute minimum amount of time. Let's use calculus to prove Snell's Law from this profound principle!

**Step 1:** The Geometric Setup.
Imagine light traveling from Point A (in medium 1 with speed $v_1$) to Point B (in medium 2 with speed $v_2$). The horizontal boundary between the mediums is the x-axis. 
Point A is at $(0, y_1)$ and Point B is at $(L, -y_2)$.
The light hits the boundary at some unknown horizontal position $x$.

**Step 2:** Define the total time $T$.
Time is Distance divided by Speed. By the Pythagorean theorem, the distances traveled in each medium are:
$D_1 = \sqrt{x^2 + y_1^2}$
$D_2 = \sqrt{(L-x)^2 + y_2^2}$
Total Time:
$$ T(x) = \frac{\sqrt{x^2 + y_1^2}}{v_1} + \frac{\sqrt{(L-x)^2 + y_2^2}}{v_2} $$

**Step 3:** Minimize the time using Calculus.
To find the exact path $x$ that minimizes time, we take the derivative of $T(x)$ and set it perfectly to $0$.
$$ \frac{dT}{dx} = \frac{1}{v_1} \cdot \frac{x}{\sqrt{x^2 + y_1^2}} + \frac{1}{v_2} \cdot \frac{-(L-x)}{\sqrt{(L-x)^2 + y_2^2}} = 0 $$

**Step 4:** Relate the geometry back to angles.
Look at the right triangles formed by the light path!
The hypotenuse of the first triangle is $D_1$. The opposite side to the angle of incidence $\theta_1$ is exactly $x$.
Therefore, $\sin\theta_1 = \frac{x}{D_1} = \frac{x}{\sqrt{x^2 + y_1^2}}$.
Likewise, $\sin\theta_2 = \frac{L-x}{D_2} = \frac{L-x}{\sqrt{(L-x)^2 + y_2^2}}$.

**Step 5:** Substitute the angles into the derivative equation.
$$ \frac{1}{v_1} \sin\theta_1 - \frac{1}{v_2} \sin\theta_2 = 0 $$
$$ \frac{\sin\theta_1}{v_1} = \frac{\sin\theta_2}{v_2} $$

**Step 6:** Convert to Index of Refraction ($n$).
We know $n = c/v$, which implies $v = c/n$. Substitute this for both velocities:
$$ \frac{\sin\theta_1}{(c/n_1)} = \frac{\sin\theta_2}{(c/n_2)} $$
Multiply both sides by $c$:
$$ n_1 \sin\theta_1 = n_2 \sin\theta_2 $$
Q.E.D. The universe naturally computes the absolute fastest path, which mathematically produces Snell's Law!
"""

topics['Modern Physics & Relativity'] = r"""# Modern Physics & Relativity: The Fabric of Reality

## 1. The Postulates of Special Relativity
In 1905, Albert Einstein completely shattered our Newtonian understanding of the universe with two simple postulates:
1. The laws of physics are identical in all inertial (non-accelerating) reference frames.
2. The speed of light in a vacuum ($c$) is exactly the same for ALL observers, regardless of how fast the observer or the light source is moving.

## 2. Time Dilation
If you shine a flashlight forward while driving a car at $0.9c$, Newton would say the light travels at $1.9c$. Einstein said the light still travels at exactly $1.0c$.
To make this mathematically possible, time itself must slow down for the moving car!
$$ \Delta t' = \gamma \Delta t $$
Where $\gamma = \frac{1}{\sqrt{1 - v^2/c^2}}$ is the Lorentz Factor.
If you travel close to the speed of light, you will age slower than your twin on Earth. This is not an optical illusion; it is a fundamental property of spacetime.

## 3. Length Contraction
Not only does time stretch, but physical space compresses. If a spaceship flies past Earth at $0.9c$, observers on Earth will measure the spaceship as physically shorter than its true length!
$$ L' = \frac{L}{\gamma} $$

## 4. Mass-Energy Equivalence
Einstein's most famous equation proved that mass is not a conserved quantity. Mass is simply a highly concentrated form of energy. They are two sides of the exact same coin.
$$ E = mc^2 $$
Because $c^2$ is an astronomically huge number ($9 \times 10^{16}$), a single paperclip contains enough latent energy to level a city—if you could completely convert its mass into pure energy.

## 5. The Photoelectric Effect
While Einstein is famous for relativity, he actually won his Nobel Prize for proving light is a particle. He showed that shining ultraviolet light on a metal plate ejects electrons, but shining intense red light does nothing. He realized light comes in quantized packets called **Photons**. A red photon simply doesn't have enough energy to knock an electron loose, no matter how many you fire!
Photon Energy: $E = hf$ (where $h$ is Planck's constant and $f$ is frequency).

## Derivation of Time Dilation
How do we prove that time slows down for moving objects using only middle-school algebra and the speed of light?

**Step 1:** The Light Clock Setup.
Imagine a "Light Clock" consisting of two mirrors facing each other, separated by a distance $L$. A single photon bounces up and down between them. One "tick" of the clock is the time it takes for the photon to bounce from the bottom, to the top, and back to the bottom.

**Step 2:** The clock at rest ($\Delta t_0$).
To an observer standing next to the stationary clock, the light travels a distance of $2L$. Since light travels at speed $c$, the time for one tick is:
$$ \Delta t_0 = \frac{2L}{c} $$

**Step 3:** The clock in motion ($\Delta t$).
Now, imagine the clock is placed on a train moving to the right at velocity $v$. To an observer standing on the ground, the photon doesn't just travel up and down. Because the mirrors are moving to the right, the photon must travel in a diagonal zig-zag path!

**Step 4:** The Pythagorean Geometry.
Let's analyze half a tick (from bottom to top).
* The vertical distance is still $L$.
* The horizontal distance the train moved is velocity times time: $v (\frac{\Delta t}{2})$.
* The diagonal distance the light traveled is $c (\frac{\Delta t}{2})$. (Crucially, Einstein's postulate says $c$ is constant!)
By the Pythagorean theorem:
$$ L^2 + \left(v \frac{\Delta t}{2}\right)^2 = \left(c \frac{\Delta t}{2}\right)^2 $$

**Step 5:** Solve for $\Delta t$.
We want to find $\Delta t$ in terms of our stationary time $\Delta t_0$.
Multiply the entire equation by 4 to remove the fractions:
$$ 4L^2 + v^2 \Delta t^2 = c^2 \Delta t^2 $$
Group the $\Delta t$ terms:
$$ 4L^2 = c^2 \Delta t^2 - v^2 \Delta t^2 $$
$$ 4L^2 = \Delta t^2 (c^2 - v^2) $$
Isolate $\Delta t^2$:
$$ \Delta t^2 = \frac{4L^2}{c^2 - v^2} $$

**Step 6:** Factor out $c^2$ in the denominator.
$$ \Delta t^2 = \frac{4L^2}{c^2 (1 - v^2/c^2)} $$
Take the square root of both sides:
$$ \Delta t = \frac{2L}{c} \cdot \frac{1}{\sqrt{1 - v^2/c^2}} $$

**Step 7:** Substitute the stationary time.
Notice that the term $\frac{2L}{c}$ is exactly equal to our stationary time $\Delta t_0$!
$$ \Delta t = \frac{\Delta t_0}{\sqrt{1 - v^2/c^2}} $$
$$ \Delta t = \gamma \Delta t_0 $$
Q.E.D. Because the denominator is less than 1, $\Delta t$ is strictly larger than $\Delta t_0$. The moving clock takes *longer* to tick. Time has mathematically dilated!
"""

topics['Nuclear Physics'] = r"""# Nuclear Physics: The Heart of the Atom

## 1. The Nucleus
The atom is almost entirely empty space. The nucleus at its center is 100,000 times smaller than the atom, yet contains 99.9% of its mass. It consists of positively charged Protons ($Z$) and neutral Neutrons ($N$). Together, they are called Nucleons.

## 2. The Strong Nuclear Force
Why doesn't the nucleus explode? You have dozens of positively charged protons packed impossibly close together, which should violently repel each other due to the Electrostatic force.
The nucleus is held together by the **Strong Nuclear Force**. It is 100 times stronger than electromagnetism, but it only operates at incredibly microscopic ranges (around $10^{-15}$ meters, or 1 femtometer). Neutrons act as the "glue" that provides extra strong force without adding any electrostatic repulsion!

## 3. Mass Defect and Binding Energy
If you put 2 individual protons and 2 individual neutrons on a scale, and then weigh an assembled Helium nucleus (which is made of the exact same 4 particles), the assembled nucleus actually weighs *less*!
This missing mass is called the **Mass Defect** ($\Delta m$).
Where did the mass go? By $E=mc^2$, it was converted into pure **Binding Energy** to hold the nucleus tightly together. To break the nucleus apart, you must inject that exact amount of energy back in.

## 4. Radioactivity and Decay
If a nucleus is too large or has a poor ratio of neutrons to protons, the short-range Strong Force can no longer overcome the long-range Electrostatic repulsion. The nucleus becomes unstable and decays.
* **Alpha Decay ($\alpha$)**: The nucleus spits out a helium nucleus (2 protons, 2 neutrons). Heavy, slow, and easily blocked by a sheet of paper.
* **Beta Decay ($\beta$)**: A neutron literally transforms into a proton by spitting out a high-speed electron! Moderately penetrating.
* **Gamma Decay ($\gamma$)**: The nucleus shifts into a lower energy state and releases a blinding flash of high-energy electromagnetic radiation (a photon). Highly penetrating and dangerous.

## 5. Fission and Fusion
* **Fission**: A massive, unstable nucleus (like Uranium-235) is struck by a neutron, causing it to violently split into two smaller nuclei, releasing immense energy and more neutrons (a chain reaction). This powers nuclear reactors and atomic bombs.
* **Fusion**: Two incredibly light nuclei (like Hydrogen) are smashed together with such intense heat and pressure that the Strong Force takes over, fusing them into a heavier element and releasing exponentially more energy than fission. This is what powers the Sun and hydrogen bombs!

## Derivation of the Radioactive Decay Law
Why does radioactive decay follow a perfectly exponential curve, $N(t) = N_0 e^{-\lambda t}$? It is a direct result of probability!

**Step 1:** The fundamental premise of probability.
In a sample of radioactive material, every single unstable nucleus is entirely independent. The probability of any specific nucleus decaying in the next microscopic second is exactly constant.
Therefore, the total number of nuclei that decay per second (the rate of change, $dN/dt$) is strictly proportional to the total number of unstable nuclei $N$ currently remaining in the sample.
$$ \frac{dN}{dt} = -\lambda N $$
Where $\lambda$ is the decay constant, representing the probability of decay per unit time. The negative sign ensures the population is decreasing.

**Step 2:** Separate the variables.
This is a first-order separable differential equation! Move $N$ to the left side and $dt$ to the right side.
$$ \frac{1}{N} dN = -\lambda \, dt $$

**Step 3:** Integrate both sides over time.
We integrate from $t=0$ (where the initial population is $N_0$) to time $t$ (where the population is $N$).
$$ \int_{N_0}^N \frac{1}{N} \, dN = \int_0^t -\lambda \, dt $$

**Step 4:** Evaluate the integrals.
The integral of $1/N$ is the natural logarithm $\ln(N)$.
$$ [\ln(N)]_{N_0}^N = -\lambda [t]_0^t $$
$$ \ln(N) - \ln(N_0) = -\lambda t $$

**Step 5:** Use logarithm properties.
$$ \ln\left(\frac{N}{N_0}\right) = -\lambda t $$

**Step 6:** Exponentiate both sides to isolate $N$.
To cancel the natural log, raise $e$ to the power of both sides.
$$ \frac{N}{N_0} = e^{-\lambda t} $$
$$ N(t) = N_0 e^{-\lambda t} $$
Q.E.D. The exponential decay formula is perfectly derived from the simple probability that rate of decay depends on the amount of material remaining!

## Derivation of Half-Life ($T_{1/2}$)
Using the decay formula, calculate the exact formula for a substance's Half-Life (the time required for exactly 50% of the material to decay).

**Step 1:** Define the Half-Life condition.
At time $t = T_{1/2}$, the remaining population $N(t)$ is exactly half of the initial population, meaning $N = \frac{1}{2}N_0$.

**Step 2:** Substitute this into the decay equation.
$$ \frac{1}{2}N_0 = N_0 e^{-\lambda T_{1/2}} $$

**Step 3:** Cancel $N_0$.
$$ \frac{1}{2} = e^{-\lambda T_{1/2}} $$

**Step 4:** Take the natural logarithm of both sides.
$$ \ln\left(\frac{1}{2}\right) = -\lambda T_{1/2} $$

**Step 5:** Simplify the logarithm.
By log rules, $\ln(1/2) = \ln(1) - \ln(2) = 0 - \ln(2) = -\ln(2)$.
$$ -\ln(2) = -\lambda T_{1/2} $$

**Step 6:** Isolate $T_{1/2}$.
The negative signs cancel.
$$ T_{1/2} = \frac{\ln(2)}{\lambda} $$
Q.E.D. The half-life is a perfect constant depending only on the probability constant $\lambda$, roughly equal to $0.693 / \lambda$.
"""

for topic, text in topics.items():
    content = replace_topic(content, topic, text)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print("Expanded Physics Batch 3 with derivations successfully.")
