export interface PremiumResults {
  summary: string[];
  flashcards: Array<{ front: string; back: string; type: string }>;
  quiz: Array<{ question: string; options: string[]; answerIndex: number }>;
  exam: Array<{ question: string; type: string }>;
  formulas: Array<{ formula: string; context: string }>;
}

export class LLMService {
  static async processDocument(text: string, apiKey: string): Promise<PremiumResults> {
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

    const prompt = `
You are a brilliant university professor analyzing a student's document (which may contain OCR errors).
Extract the core knowledge, equations, and facts from the following text and format your response STRICTLY as a JSON object with the following schema:
{
  "summary": ["Bullet point 1", "Bullet point 2", "Bullet point 3 (at least 3, max 6)"],
  "flashcards": [
    {"front": "Question here", "back": "Answer here", "type": "definition/concept/equation"} 
    // strictly 8 to 15 flashcards
  ],
  "quiz": [
    {
      "question": "Multiple choice question",
      "options": ["Option 1", "Option 2", "Option 3", "Option 4"],
      "answerIndex": 0 // index of the correct option (0-3)
    } // exactly 5 quiz questions
  ],
  "exam": [
    {"question": "Deep essay or analytical question", "type": "Essay"},
    {"question": "Calculation or scenario question", "type": "Short Answer"}
    // exactly 4 questions
  ],
  "formulas": [
    {"formula": "A = B", "context": "What this equation represents"}
    // extract all distinct math/physics/chemistry formulas or equations. Fix obvious OCR errors (e.g. x2 -> x^2)
  ]
}

DO NOT wrap the response in markdown \`\`\`json blocks. Just return the raw JSON object.

DOCUMENT TEXT:
---
${text.slice(0, 30000)}
---
`;

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{ text: prompt }]
        }],
        generationConfig: {
          temperature: 0.1, // Keep it deterministic
          responseMimeType: "application/json",
        }
      })
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.error?.message || `Gemini API Error: ${response.status}`);
    }

    const data = await response.json();
    const candidateText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!candidateText) {
      throw new Error("No response generated by the AI.");
    }

    try {
      // Sometimes it still wraps in markdown despite instructions, so clean it
      const cleanJson = candidateText.replace(/```json/gi, '').replace(/```/gi, '').trim();
      const parsed = JSON.parse(cleanJson);
      
      // Basic validation
      if (!parsed.summary || !parsed.flashcards || !parsed.quiz || !parsed.exam || !parsed.formulas) {
        throw new Error("Invalid response format from AI.");
      }
      
      return parsed as PremiumResults;
    } catch (err) {
      console.error("Failed to parse Gemini JSON:", err, candidateText);
      throw new Error("Failed to parse the AI's response into the correct format.");
    }
  }
}
