export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Use the server's environment variable by default, but allow overriding if the user provides one (for BYOK)
  const apiKey = req.body.apiKey || process.env.GEMINI_API_KEY;

  if (!apiKey) {
    return res.status(500).json({ 
      error: 'Backend Configuration Error: The server is missing the GEMINI_API_KEY environment variable. The developer must add this in the Vercel Dashboard.'
    });
  }

  try {
    const text = req.body.text;
    if (!text) {
      return res.status(400).json({ error: 'No text provided' });
    }

    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

    const prompt = `
You are a brilliant university professor analyzing a student's document (which may contain OCR errors).
Extract the core knowledge, equations, and facts from the following text and format your response STRICTLY as a JSON object with the following schema:
{
  "summary": ["Bullet point 1", "Bullet point 2", "Bullet point 3 (at least 3, max 6)"],
  "flashcards": [
    {"front": "Question here", "back": "Answer here", "type": "definition/concept/equation"} 
  ],
  "quiz": [
    {
      "question": "Multiple choice question",
      "options": ["Option 1", "Option 2", "Option 3", "Option 4"],
      "answerIndex": 0
    }
  ],
  "exam": [
    {"question": "Deep essay or analytical question", "type": "Essay"},
    {"question": "Calculation or scenario question", "type": "Short Answer"}
  ],
  "formulas": [
    {"formula": "A = B", "context": "What this equation represents"}
  ]
}

DO NOT wrap the response in markdown \`\`\`json blocks. Just return the raw JSON object.

DOCUMENT TEXT:
---
${text.slice(0, 30000)}
---
`;

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.1,
          responseMimeType: "application/json",
        }
      })
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      return res.status(response.status).json({ error: errorData.error?.message || 'Gemini API Error' });
    }

    const data = await response.json();
    const candidateText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!candidateText) {
      return res.status(500).json({ error: "No response generated by the AI." });
    }

    // Clean markdown wrappers
    const cleanJson = candidateText.replace(/```json/gi, '').replace(/```/gi, '').trim();
    const parsed = JSON.parse(cleanJson);
    
    return res.status(200).json(parsed);

  } catch (error) {
    console.error("Vercel Backend Error:", error);
    return res.status(500).json({ error: error.message || 'Internal Server Error' });
  }
}
